name: Assignment1

on:
  push:
    paths:
      - 'C:\Users\Shashank Kanade\OneDrive\Desktop\devops\lab1-github-GHactions\student_note.md' 
jobs:
  print-info:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.repository }}
      STUDENT_USERNAME: ${{ github.actor }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Printing Details
        run: |
          echo "Repo Name: $REPO_NAME"
          echo "Student Username: $STUDENT_USERNAME"
